dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pydiatra pyflakes
- $if_pygments pip install restructuredtext-lint pygments
script:
- ./chemiscripts '3(NH4)2S + Sb2S5 -> 6NH4+ + 2SbS4 3+'
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pygments restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
